### ISSUE TITLE
Instalar plugins de monitoramento nos servidores APyB Zabbix e/ou Munin e monitorar aplicações

### ISSUE THREAD

**Issue by rudaporto** [apyb/apyb.gerenciamento#23]
Conseguir o recursos de servidores de monitoramento Zabbix (Osvaldo disse que pode usar o dele) e Munin (vou falar com o Xiru se ele pode emprestar o dele).

Usando essas ferramentas devemos ter indicadores constantes de desempenho do ambiente e bem como receber alertas de aviso em caso de problemas de segurança, espaço em disco, latência de disco, load alto, etc.

Finalmente, é possível monitorar também as aplicações web para que sejamos avisados em caso de qualquer falha e possamos resolver o problema o quanto antes.

**Comment by rougeth** [comment]
Fechando issue, já que todos os sites da APyB foram migrados e agora são estáticos. O único site não estático está no Heroku (associados.python.org.br).
