### ISSUE TITLE
Definir um política de backup e uma estratégia de retenção dos backups e plano de recuperação

### ISSUE THREAD

**Issue by rudaporto** [apyb/apyb.gerenciamento#24]
Hoje a APyB hospeda alguns serviços por conta própria e não temos definido claramente uma política de backup e um procedimento para recuperação do ambiente em caso de falhas.

Isso na verdade deveria cobrir todos os serviços, mesmo os hospedados em terceiros para que exista uma documentação clara de como restabelecer os serviços e como fazer deploy dos ambientes em caso de ser preciso recuperar em outro local que não seja o original.

Para questão do backup o que temos hoje é um rsync e não realiza retenção e não guarda qualquer histórico para recuperação em caso de alteração acidental ou provocada, ou exclusão de dados e perda de integridade.

**Comment by rougeth** [comment]
Criei uma issue para automatizar backup do banco de dados do site dos associados (heroku): https://github.com/apyb/tarefas/issues/23
