### ISSUE TITLE
Encaminhar questões de registro de marcas relacionadas a Python no Brasil

### ISSUE THREAD

**Issue by osantana** [apyb/apyb.gerenciamento#27]
Buscar apoio (inclusive financeiro) da:
- PSF
- Plone Foundation
- Zope Foundation
- Django Foundation
- Web2Py/Massimo (PSF?)

Para dar encaminhamento no registro das marcas:
- Python
- Django
- Plone
- Zope
- Web2Py

Através da contratação de um escritório de registro de marcas e gerenciamento do processo.

Esse processo é importante para evitar eventuais problemas como o que está acontecendo na UE: http://pyfound.blogspot.com.br/2013/02/python-trademark-at-risk-in-europe-we.html

**Comment by rochacbruno** [comment]
Acho que isso pode ser fechado não? ainda faz sentido registrar essas marcas?

**Comment by taniaa** [comment]
Está parada, não foi resolvida e ainda há o risco de ocorrer o que falamos acima. 

Por mim, deixa aberto.

**Comment by rougeth** [comment]
Nº do Processo: 918321263
Marca: PYTHON
Situação: Registro de marca em vigor
Apresentação: Nominativa
Natureza: De Serviço
Titular(1): | PYTHON SOFTWARE FOUNDATION

https://busca.inpi.gov.br/pePI/servlet/MarcasServletController?Action=detail&CodPedido=4048435
