### ISSUE TITLE
Verificar erro portal_setup -> CMFEditions

### ISSUE THREAD

**Issue by ramiroluz** [apyb/apyb.gerenciamento#31]
Ao tentar publicar arquivo pdf, na pasta financeiro/2013.

Ocorreu o seguinte erro:
Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module Products.CMFPlone.FactoryTool, line 453, in **call**
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91,
in **call**
  Module Products.CMFFormController.BaseControllerPageTemplate, line
28, in _call
  Module Products.CMFFormController.ControllerBase, line 231, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 35, in __call__
ValueError: Unable to find update_version_before_edit

Seguidas as orientações dessa discussão:
http://stackoverflow.com/questions/12513123/unable-to-add-content-to-new-plone-site-valueerror-unable-to-find-update-versi

Go to zmi -> portal_setup -> tab "import" -> select "CMFEditions" in
the dropdown menu -> than hit the "import all steps" button.

Resolveu, mas tem um erro num produto:
Products.ATGoogleVideo.setuphandlers.setupATGoogleVideo

**Comment by rougeth** [comment]
Fechando issue, já que todos os sites da APyB foram migrados e agora são estáticos.
