### ISSUE TITLE
Atualizar documentação sobre moderação da lista python-brasil

### ISSUE THREAD

**Issue by taniaa** [apyb/apyb.gerenciamento#32]
http://associacao.python.org.br/workarea/procedimentos-web/moderacao-pythonbrasil/

A página está privada e está como texto estruturado na hora da edição no site.

1) Eu acrescentaria:
"
Em XXXX o serviço foi migrado para os `Grupos do Google <http://groups.google.com>`_ endereço python-brasil@googlegroups.com.
"

2) Revisaria quem são os moderadores.

3) Adicionaria o processo descrito pelo Werneck, como boa prática de moderação.

Não atualizei porque não sou moderadora desta lista, não tenho conhecimento do processo dia a dia e não tenho conhecimento completo de como deveria ser (pela experiência).

**Comment by rougeth** [comment]
- Donos (apenas emails institucionais python.org.br:
  - webmaster@
  - tecnologia@
- Moderação:
  - Atual gestão da APyB @apyb/diretoria 

Vou adicionar na documentação de transição de gestão a mudança de moderação das listas.
