### ISSUE TITLE
wiki - Atualizar pagina InicieSe

### ISSUE THREAD

**Issue by luzfcb** [apyb/apyb.gerenciamento#61]
https://www.python.org.br/wiki/InicieSe
- [ ] Atualizar tutorial de instalação da maquina virtual no windows para Python3
- [ ] Incluir botão explicito e grande para a pagina de download da maquina virtual
- [ ] Atualizar lista de IDE's
- [ ] Atualizar lista de editores de texto e incluir screenshots
- [ ] Incluir links para interpretador onlines

**Comment by mazulo** [comment]
Se acessar o site usando `https` receberá um "This webpage is not available". Creio que esteja relacionado com esta issue #56 sobre os certificados.

Btw me disponho para fazer esta atualização

**Comment by rougeth** [comment]
Mesmo comentário da issue https://github.com/apyb/apyb.gerenciamento/issues/62

Fechando essa issue. Se vocês toparem rever esse tópico e ainda fizer sentido, vamos criar um issue no repositório do site.

https://github.com/pythonbrasil/wiki
