### ISSUE TITLE
wiki - Atualizar pagina ImpressioneSe

### ISSUE THREAD

**Issue by luzfcb** [apyb/apyb.gerenciamento#62]
A pagina `https://www.python.org.br/wiki/ImpressioneSe` tem sido utilizada para em varias campanhas de marketing no Facebook, contudo ela possui informações muito desatualizadas o que acaba sendo marketing mais danoso do que benéfico para nossa comunidade. 

Se eu fosse um desavisado e encontrasse aquela pagina, com toda certeza eu iria procurar outra coisa pra aprender, menos Python, pois aquela pagina de impressionante não tem nada.
- [ ] Colocar as logomarcas dos principais Framework e links para os mesmos (acho que links para tutoriais/video-aulas de cada um também seria bom)
- [ ] Atualizar lista de aplicações Python para gestão empresarial
- [ ] Remover e/ou atualizar imagem e referencias ao nokia S60 (quem compra e vende isso em 2014?)
- [ ] Incluir Kivy
- [ ] Incluir outros frameworks para criação de jogos que utilizam Python
- [ ] Incluir mais referencias a bibliotecas uteis no meio cientifico, como o Pandas e outras
- [ ] Incluir mais referencias a bibliotecas para educação, como `turtle` que vem com Python3.4 e outras utilizações com Arduino, RaspberryPi
- [ ] Incluir coisas realmente impressionantes.

**Comment by rougeth** [comment]
@luzfcb fechando a issue. Se você topar rever esse tópico e ainda fizer sentido, cria um issue no repositório do site, por favor.

https://github.com/pythonbrasil/wiki
