### ISSUE TITLE
Tentar renomear a conta no YouTube

### ISSUE THREAD

**Issue by taniaa** [apyb/apyb.gerenciamento#8]
Por um equívoco de exclusão que fizeram, tentar retomar a conta PythonBrasil e mover os vídeos da conta PythonBrazil para ela.

**Comment by gilsondev** [comment]
Alguma novidade disso? Conseguiu resolver?

**Comment by taniaa** [comment]
Não resolveu. Tem que ver com alguém no YouTube. Ainda acho necessário.

**Comment by gilsondev** [comment]
Sabe de alguém que pode nos ajudar?

**Comment by taniaa** [comment]
É correr atrás de alguém influente, acho. Pode ir atrás pelas vias formais, se não der certo procurar alguém com cacique lá dentro... IMHO.

**Comment by diegorocha** [comment]
+1

**Comment by humrochagf** [comment]
não consegui renomear para pegar a url, o que tem como é só trocar o nome no título. 
a outra alternativa é criar um canal pythonbrasil e mover os vídeos pra ela se quiser a url aí fica pra decidir o que é melhor:
1. Trocar o título
2. Criar canal e mover os vídeos

**Comment by taniaa** [comment]
Faz mais sentido criar canal e mover os vídeos.

Mas quão trabalhoso isso seria? É tipo selecionar todos e mover ou um a um? Será que perde as visualizações?

Abraço!

**Comment by humrochagf** [comment]
Este é o problema, como o google não oferece essa feature, tem que baixar e subir denovo no outro canal

**Comment by ramiroluz** [comment]
Seguinte, eu me confundi e subi alguns vídeos para pythonbrasil, outros
para pythonbrazil.

Devo apagar os vídeos de qual canal? z ou s?

2015-07-16 10:11 GMT-03:00 Humberto Rocha notifications@github.com:

> Este é o problema, como o google não oferece essa feature, tem que baixar
> e subir denovo no outro canal
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pythonbrasil/apyb.gerenciamento/issues/8#issuecomment-121951593
> .

## 

## 

-- Ramiro Batista da Luz
-- (41) 9173-2231
-- http://www.ramiroluz.eti.br

**Comment by rougeth** [comment]
Adicionei na descrição do canal:

> Canal Antigo da Python Brasil - Para vídeos novos visite: https://www.youtube.com/c/pythonbrasiloficial

https://www.youtube.com/c/pythonbrazil

Vou fechar essa issue, não acho que vale a pena baixar e refazer o upload de todos os vídeos.
