### ISSUE TITLE
Organizar espaço ocupado na rackspace

### ISSUE THREAD

**Issue by filipecifali** [apyb/apyb.gerenciamento#80]
Esta issue deve ser fechada somente após a restauração de todos os sites para podermos remover os diretórios /backup

**Comment by filipecifali** [comment]
Falta terminar de revisar o /backup do plone.apybr (104.239.163.48)

Outros servidores:

Filesystem      Size  Used Avail Use% Mounted on
rootfs           20G  3.4G   16G  18% /

Filesystem      Size  Used Avail Use% Mounted on
rootfs           20G  1.8G   17G  10% /

**Comment by rougeth** [comment]
Fechando issue, já que todos os sites da APyB foram migrados e agora são estáticos.
