### ISSUE TITLE
Redirecionamento django.org.br/documentacao para docs.djangobrasil.org

### ISSUE THREAD

**Issue by filipecifali** [apyb/apyb.gerenciamento#81]
http://django.org.br/documentacao/  ele redireciona para http://docs.djangobrasil.org

Não estava no template do projeto, necessário localizar onde está o link e apontar ao novo endereço.

**Comment by filipecifali** [comment]
Subdomínio criado e apontado para o servidor, ainda necessário encontrar o endereço e fazer ele funcionar

**Comment by decko** [comment]
@filipecifali, o endereço http://django.org.br/documentacao está apontando para o docs.djangobrasil.org. Podemos fechar esta issue?

**Comment by filipecifali** [comment]
Acho incorreto fechar ela pois não está funcionando o docs.djangobrasil.org ainda.

Infelizmente fiquei sem tempo esta semana para continuar as tarefas.

**Comment by decko** [comment]
@filipecifali Entendi. Pelo q eu pude ver é algo nas regras de VirtualHost do apache. A primeira regra é demasiadamente abrangente, logo, qualquer chamada para subdominios é atendida logo no inicio. Como vc abriu a issue, achei melhor não mexer nos arquivos, mas se precisar estamos às ordens.

**Comment by filipecifali** [comment]
@decko Você pode fazer essa config? Pode mexer sim, basta testar as URLs depois de mexer para garantir que elas estão funcionando.

**Comment by mazulo** [comment]
Iae galera, beleza? Então, há um tempo quando foi lançado no Twitter o novo site http://docs.djangobrasil.org/, o qual cobriria a versão 1.6 do Django, eu reportei o erro que originou esta issue. Alguém saberia informar se já foi consertado?

Edit: Fui acessar também a primeira [parte do tutorial](http://docs.djangobrasil.org/intro/tutorial01.html) e notei que não, bem como a presença do `DEBUG = True`

**Comment by gilsondev** [comment]
Sobre atualização do djangobrasil, não seria interessante "forkar" o site do djangoproject, e adaptarmos para o Brasil?

Segue o repositório: https://github.com/django/djangoproject.com

**Comment by filipecifali** [comment]
Seria, principalmente usar um serviço de tradução ou algo assim e sugerirmos que o projeto principal use ele também. 

É muito complicado fazer isso? Por mim é tranquilo deixar uma app, já é uma app django rodando para o portal, mas acho que seria mais interessante deixarmos um conteúdo estático porque o portal em si somente tem iterações de feed de notícias, não necessariamente necessitando da app inteira rodando pra isso ao meu ver.

O que acharem melhor, por mim, atualmente o site roda num Lighttpd / Lighty, seria interessante até trocar ele para um Nginx e depois adicionarmos um Varnish na frente de todos os Nginx.

**Comment by gilsondev** [comment]
@filipecifali  acha melhor mudar o site para usar o Pelican mesmo?

**Comment by filipecifali** [comment]
Acho que a melhor solução é pensarmos em algo que fique fácil para modificarmos num dia que precisarmos.

O @cadu-leite já está trabalhando com Markdown (se não me engano) no site da PythonBrasil 2015, então como o Pelican trabalha com Markdown também é uma boa solução atualmente, pois poderemos inclusive deixar os futuros "legados" em Markdown também usando ele.

Meu voto é para usar o Pelican porque vai funcionar para diversos casos.

+1

**Comment by gilsondev** [comment]
Se o objetivo é tornar mais acessível a manutenção, backup e criação de novos conteúdos, o Pelican é uma boa escolha mesmo.

**Comment by diegorocha** [comment]
Pelican (ou qualquer outro gerador de HTML a partir de markdown/reStructuredText a escolha) +1

**Comment by taniaa** [comment]
Oi, pesssoal. Esta issue foi resolvida? Navegando pelo site tem link que funciona[1], outros dão not found[2] e outros not found apresentado de outra forma[3]...

[1] http://docs.djangobrasil.org/casos-de-sucesso/
[2] https://www.djangoproject.com/documentation/model_api/
[3] http://docs.djangobrasil.org/intro/overview.html

**Comment by mazulo** [comment]
E aí, pessoal, bora mudar o site para o Pelican? :) +1 nele também.

**Comment by rougeth** [comment]
Não consegui encontrar onde o djangobrasil.org está registrado (ou se ainda está registrado com a APyB). Ainda temos django.org.br no registro.br, mas vou fechar a issue. Se alguém ainda tiver interesse, mande uma mensagem no [/apyb/comunidade](https://github.com/apyb/comunidade/discussions).
