### ISSUE TITLE
Atualizar versão do Python no Plone.org.br

### ISSUE THREAD

**Issue by taniaa** [apyb/apyb.gerenciamento#9]
Após restauração de ambiente no final de semana pelo Rudá, notei que não aparece a opção de Itens Relacionados no site Plone.org.br.

Sugeri ao Rudá atualizar a versão do Python de 2.6.6 para 2.7.2, como está nos sites da APyB e PythonBrasil[9], com Plone 4.2.

**Comment by taniaa** [comment]
Na verdade, com a descontinuação dos serviços no servidor anterior no final do ano passado, ainda será preciso subir este site aqui tb...

Não consigo identificá-lo no backup do novo servidor para tentar subir.

@rudaporto me ajuda? São muito nomes parecidos...

**Comment by rougeth** [comment]
Acredito que essa issue não é mais necessária, já que todos os sites foram migrados para arquivos estáticos. Fechando.
